CREATE TABLE User (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role ENUM('buyer', 'seller', 'customer_rep', 'admin') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Category (
    CategoryID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE Subcategory (
    SubcategoryID INT PRIMARY KEY AUTO_INCREMENT,
    CategoryID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE
);

CREATE TABLE Item (
    ItemID INT PRIMARY KEY AUTO_INCREMENT,
    Brand VARCHAR(50) NOT NULL,
    Model VARCHAR(100) NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Description TEXT,
    Condition ENUM('New', 'Refurbished', 'Used', 'Open Box') NOT NULL,
    OwnerID INT NOT NULL,
    CategoryID INT NOT NULL,
    SubcategoryID INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('active', 'withdrawn', 'sold') DEFAULT 'active' NOT NULL,
    FOREIGN KEY (OwnerID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE,
    FOREIGN KEY (SubcategoryID) REFERENCES Subcategory(SubcategoryID) ON DELETE CASCADE
);

CREATE TABLE Attribute (
    AttributeID INT PRIMARY KEY AUTO_INCREMENT,
    SubcategoryID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    FOREIGN KEY (SubcategoryID) REFERENCES Subcategory(SubcategoryID) ON DELETE CASCADE
);

CREATE TABLE ItemAttributeValue (
    ItemID INT NOT NULL,
    AttributeID INT NOT NULL,
    Value VARCHAR(100),
    PRIMARY KEY (ItemID, AttributeID),
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE CASCADE,
    FOREIGN KEY (AttributeID) REFERENCES Attribute(AttributeID) ON DELETE CASCADE
);

CREATE TABLE Auction (
    AuctionID INT PRIMARY KEY AUTO_INCREMENT,
    ItemID INT NOT NULL,
    StartPrice DECIMAL(10,2) NOT NULL,
    MinIncrement DECIMAL(10,2) NOT NULL,
    SecretMinPrice DECIMAL(10,2) NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    IsClosed BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE CASCADE
);

CREATE TABLE Bid (
    BidID INT PRIMARY KEY AUTO_INCREMENT,
    AuctionID INT NOT NULL,
    BidderID INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    BidTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaxAutoBid DECIMAL(10,2),
    FOREIGN KEY (AuctionID) REFERENCES Auction(AuctionID) ON DELETE CASCADE,
    FOREIGN KEY (BidderID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE Transaction (
    TransactionID INT PRIMARY KEY AUTO_INCREMENT,
    AuctionID INT NOT NULL,
    BuyerID INT NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    TransactionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('completed', 'pending', 'cancelled') DEFAULT 'completed',
    FOREIGN KEY (AuctionID) REFERENCES Auction(AuctionID) ON DELETE CASCADE,
    FOREIGN KEY (BuyerID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE Alert (
    AlertID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Subcategory VARCHAR(50) NOT NULL,
    SearchCriteria JSON NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE Notification (
    NotificationID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    Message TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('unread', 'read') DEFAULT 'unread',
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE CustomerRep (
    RepID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    AssignedBy INT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    Department VARCHAR(50),
    Shift VARCHAR(20),
    Status ENUM('active', 'inactive') DEFAULT 'active',
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (AssignedBy) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE Admin (
    AdminID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT UNIQUE NOT NULL,
    AccessLevel ENUM('SuperAdmin', 'Manager', 'ReadOnly') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastLogin DATETIME,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE CustomerQuery (
    QueryID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    Subject VARCHAR(100) NOT NULL,
    Message TEXT NOT NULL,
    Response TEXT,
    ResponseBy INT,
    ResponseAt DATETIME,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('open', 'closed') DEFAULT 'open',
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (ResponseBy) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE FAQ (
    FAQID INT PRIMARY KEY AUTO_INCREMENT,
    Question TEXT NOT NULL,
    Answer TEXT NOT NULL
);

